services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: apidebugger
    ports: ["5434:5432"]

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: ["5050:80"]
    depends_on: [db]
