services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: apidebugger
    ports: ["5434:5432"]
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d:ro

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: ["5050:80"]
    depends_on: [db]

  worker:
    build:
      context: ../worker
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    env_file:
      - .env                   # PG_DSN, AIP_URL, AIP_TOKEN
    ports:
      - "5001:5001"            # ← host:container now matches Flask’s 5001
    depends_on:
      - db

  proxy:
    platform: linux/arm64
    build:
      context: ..
      dockerfile: proxy/Dockerfile
    depends_on: [db]
    ports: ["8080:8080"]
    environment:
      PG_DSN: host=db port=5432 dbname=postgres user=postgres password=apidebugger